/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BrandInquiry {
  'id' : bigint,
  'contactName' : string,
  'createdAt' : Time,
  'email' : string,
  'website' : string,
  'brandName' : string,
  'campaignGoal' : string,
  'budgetRange' : string,
  'industry' : string,
  'timeline' : string,
}
export interface Campaign {
  'id' : bigint,
  'status' : string,
  'createdAt' : Time,
  'commission' : bigint,
  'brandId' : bigint,
  'dealValue' : bigint,
  'influencerId' : bigint,
}
export interface InfluencerApplication {
  'id' : bigint,
  'portfolioLink' : string,
  'followersCount' : bigint,
  'createdAt' : Time,
  'instagramHandle' : string,
  'fullName' : string,
  'engagementRate' : bigint,
  'email' : string,
  'approved' : boolean,
  'niche' : string,
  'location' : string,
  'rateCard' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveInfluencer' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCampaign' : ActorMethod<[Campaign], undefined>,
  'getAggregateStats' : ActorMethod<
    [],
    { 'totalCommission' : bigint, 'totalDealValue' : bigint }
  >,
  'getAllBrands' : ActorMethod<[], Array<BrandInquiry>>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllInfluencers' : ActorMethod<[], Array<InfluencerApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isInfluencerApproved' : ActorMethod<[bigint], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitBrandInquiry' : ActorMethod<[BrandInquiry], undefined>,
  'submitInfluencerApplication' : ActorMethod<
    [InfluencerApplication],
    undefined
  >,
  'updateCampaignDealValue' : ActorMethod<[bigint, bigint], undefined>,
  'updateCampaignStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];