/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : Time,
  'commission' : IDL.Nat,
  'brandId' : IDL.Nat,
  'dealValue' : IDL.Nat,
  'influencerId' : IDL.Nat,
});
export const BrandInquiry = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'brandName' : IDL.Text,
  'campaignGoal' : IDL.Text,
  'budgetRange' : IDL.Text,
  'industry' : IDL.Text,
  'timeline' : IDL.Text,
});
export const InfluencerApplication = IDL.Record({
  'id' : IDL.Nat,
  'portfolioLink' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : Time,
  'instagramHandle' : IDL.Text,
  'fullName' : IDL.Text,
  'engagementRate' : IDL.Nat,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'niche' : IDL.Text,
  'location' : IDL.Text,
  'rateCard' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveInfluencer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCampaign' : IDL.Func([Campaign], [], []),
  'getAggregateStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalCommission' : IDL.Nat, 'totalDealValue' : IDL.Nat })],
      ['query'],
    ),
  'getAllBrands' : IDL.Func([], [IDL.Vec(BrandInquiry)], ['query']),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllInfluencers' : IDL.Func(
      [],
      [IDL.Vec(InfluencerApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isInfluencerApproved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitBrandInquiry' : IDL.Func([BrandInquiry], [], []),
  'submitInfluencerApplication' : IDL.Func([InfluencerApplication], [], []),
  'updateCampaignDealValue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateCampaignStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : Time,
    'commission' : IDL.Nat,
    'brandId' : IDL.Nat,
    'dealValue' : IDL.Nat,
    'influencerId' : IDL.Nat,
  });
  const BrandInquiry = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'brandName' : IDL.Text,
    'campaignGoal' : IDL.Text,
    'budgetRange' : IDL.Text,
    'industry' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const InfluencerApplication = IDL.Record({
    'id' : IDL.Nat,
    'portfolioLink' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : Time,
    'instagramHandle' : IDL.Text,
    'fullName' : IDL.Text,
    'engagementRate' : IDL.Nat,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'niche' : IDL.Text,
    'location' : IDL.Text,
    'rateCard' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveInfluencer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCampaign' : IDL.Func([Campaign], [], []),
    'getAggregateStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCommission' : IDL.Nat,
            'totalDealValue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllBrands' : IDL.Func([], [IDL.Vec(BrandInquiry)], ['query']),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllInfluencers' : IDL.Func(
        [],
        [IDL.Vec(InfluencerApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isInfluencerApproved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitBrandInquiry' : IDL.Func([BrandInquiry], [], []),
    'submitInfluencerApplication' : IDL.Func([InfluencerApplication], [], []),
    'updateCampaignDealValue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateCampaignStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };